### ISSUE TITLE
PureMVC package; cannot find entry point

### ISSUE THREAD

**Issue by sparkbuzz** [jspm/registry#424]
I've tried to add both the standard and multicore versions of the PureMVC library, and tested with the following snippet from the command line:

` jspm install puremvc=github:PureMVC/puremvc-typescript-standard-framework -o '{"main": "bin/puremvc-typescript-standard-1.0"}' `

When I run the above, the library installs ok, so I've created the overrides in *package-overrides/GitHub/PureMVC/*. My changes have been merged to master so I clear the JSPM cache with

` jspm cache-clear `

and install with

` jspm install puremvc-standard `

Everything downloads, and installs but the override file does not get created, and I get the following error output:

> $ jspm install puremvc-standard
>     Creating registry cache...
>     Looking up github:PureMVC/puremvc-typescript-standard-framework
>     Downloading github:PureMVC/puremvc-typescript-standard-framework@1.0.0
>
>warn Main entry point not found for github:PureMVC/puremvc-typescript-standard-framework@1.0.0.
>     Adjust this property in the package.json or with an override, setting "main": false if this is the intention.
>
>ok   Installed puremvc-standard as github:PureMVC/puremvc-typescript-standard-framework@^1.0.0 (1.0.0)
>ok   Install tree has no forks.
>
>ok   Install complete.

Can anyone please help me out and spot what's I'm doing wrong?

**Comment by sparkbuzz** [comment]
I've made a PR as part of this investigation: https://github.com/jspm/registry/pull/425

**Comment by guybedford** [comment]
@sparkbuzz I've fixed the override naming in https://github.com/jspm/registry/commit/93a5f4dcfe011df64100906f8e5a6c4da00325bc. This should be working now.

**Comment by sparkbuzz** [comment]
Just did another test with `jspm install -f puremvc-standard` and still getting an error:

> warn Main entry point not found for github:PureMVC/puremvc-typescript-standard-framework@1.0.0.

When I run `jspm install puremvc=github:PureMVC/puremvc-typescript-standard-framework -o '{"main": "bin/puremvc-typescript-standard-1.0.js"}'` everything works perfectly, I don't understand why the override fails...

**Comment by guybedford** [comment]
It wasn't referencing the right file - https://github.com/jspm/registry/blob/master/package-overrides/github/PureMVC/puremvc-typescript-multicore-framework@1.0.0.json.

The main should be correct now finally. Will definitely work on better warnings / suggestions for this stuff.

**Comment by guybedford** [comment]
See the correction in https://github.com/jspm/registry/commit/cba17fd14b4e199cdf2e7fae410351cdb1fdc22c.
